# Generated by Django 5.2.7 on 2026-04-07 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('high_admin', 'Admin'), ('nutritionist', 'Nutritionist'), ('client', 'Client')], max_length=20, null=True),
        ),
    ]
