# Generated by Django 5.2.12 on 2026-04-06 14:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
        ('nutritionist', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('total_paid', models.FloatField(blank=True, null=True)),
                ('commission_rate', models.FloatField(blank=True, null=True)),
                ('net_earnings', models.FloatField(blank=True, null=True)),
                ('item_type', models.CharField(blank=True, choices=[('plan', 'Plan'), ('consultation_advice', 'Consultation Advice'), ('consultation_custom', 'Consultation Custom')], max_length=30, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(db_column='client_id', on_delete=django.db.models.deletion.CASCADE, to='client.client')),
                ('nutritionist', models.ForeignKey(db_column='nutritionist_id', on_delete=django.db.models.deletion.CASCADE, to='nutritionist.nutritionist')),
            ],
            options={
                'db_table': 'invoices',
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_image_url', models.CharField(default='default_plan_cover.jpg', max_length=255)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('plan_type', models.CharField(blank=True, choices=[('private-custom', 'Private Custom'), ('public-predefined', 'Public Predefined')], max_length=30, null=True)),
                ('content_json', models.JSONField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('duration_days', models.IntegerField(blank=True, null=True)),
                ('free_consultations_per_week', models.IntegerField(default=0)),
                ('rating_avg', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('deleted', 'Deleted')], default='pending', max_length=20)),
                ('creator', models.ForeignKey(db_column='creator_id', on_delete=django.db.models.deletion.CASCADE, to='nutritionist.nutritionist')),
                ('target_client', models.ForeignKey(blank=True, db_column='target_client_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.client')),
            ],
            options={
                'db_table': 'plans',
            },
        ),
        migrations.CreateModel(
            name='PlanModerationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(blank=True, max_length=50, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(db_column='admin_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(db_column='plan_id', on_delete=django.db.models.deletion.CASCADE, to='marketplace.plan')),
            ],
            options={
                'db_table': 'plan_moderation_logs',
            },
        ),
        migrations.CreateModel(
            name='ServiceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(blank=True, choices=[('plan', 'Plan'), ('consultation', 'Consultation')], max_length=20, null=True)),
                ('item_id', models.IntegerField(blank=True, null=True)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(db_column='client_id', on_delete=django.db.models.deletion.CASCADE, to='client.client')),
            ],
            options={
                'db_table': 'service_reviews',
            },
        ),
        migrations.CreateModel(
            name='UserPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_day_index', models.IntegerField(default=0)),
                ('status', models.CharField(blank=True, choices=[('active', 'Active'), ('completed', 'Completed')], max_length=20, null=True)),
                ('free_consultations_used', models.IntegerField(default=0)),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(db_column='client_id', on_delete=django.db.models.deletion.CASCADE, to='client.client')),
                ('plan', models.ForeignKey(db_column='plan_id', on_delete=django.db.models.deletion.CASCADE, to='marketplace.plan')),
            ],
            options={
                'db_table': 'user_plans',
            },
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('zoom_link', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('notified', 'Notified'), ('finished', 'Finished'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('consultation_type', models.CharField(choices=[('advice_only', 'Advice Only'), ('plan_included', 'Plan Included'), ('custom_plan_session', 'Custom Plan Session')], default='advice_only', max_length=30)),
                ('price_paid', models.FloatField(default=0)),
                ('nutritionist_commission', models.FloatField(blank=True, null=True)),
                ('is_free_from_plan', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(db_column='client_id', on_delete=django.db.models.deletion.CASCADE, to='client.client')),
                ('nutritionist', models.ForeignKey(db_column='nutritionist_id', on_delete=django.db.models.deletion.CASCADE, to='nutritionist.nutritionist')),
                ('user_plan', models.ForeignKey(blank=True, db_column='user_plan_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketplace.userplan')),
            ],
            options={
                'db_table': 'consultations',
            },
        ),
        migrations.CreateModel(
            name='PlanRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(db_column='client_id', on_delete=django.db.models.deletion.CASCADE, to='client.client')),
                ('plan', models.ForeignKey(db_column='plan_id', on_delete=django.db.models.deletion.CASCADE, to='marketplace.plan')),
            ],
            options={
                'db_table': 'plan_ratings',
                'unique_together': {('plan', 'client')},
            },
        ),
    ]
