# Generated by Django 5.2.7 on 2026-09-07 03:45

from django.db import migrations, models


def deduplicate_service_reviews(apps, schema_editor):
    """Remove duplicate ServiceReview rows, keeping only the latest one per (client, item_type, item_id)."""
    ServiceReview = apps.get_model('marketplace', 'ServiceReview')
    from django.db.models import Max

    # Find all duplicate groups
    dupes = (
        ServiceReview.objects
        .values('client_id', 'item_type', 'item_id')
        .annotate(max_id=Max('id'))
        .filter(item_type__isnull=False, item_id__isnull=False)
    )

    keep_ids = set()
    for d in dupes:
        keep_ids.add(d['max_id'])

    # Delete all reviews NOT in the keep set, where there are duplicates
    for d in dupes:
        ServiceReview.objects.filter(
            client_id=d['client_id'],
            item_type=d['item_type'],
            item_id=d['item_id'],
        ).exclude(id=d['max_id']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_client_activity_level_client_diet'),
        ('marketplace', '0002_checkoutsession'),
        ('nutritionist', '0003_alter_nutritionistlanguage_id'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='consultation',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['scheduled', 'notified'])), fields=('nutritionist', 'appointment_date', 'start_time'), name='unique_active_consultation_slot'),
        ),
        migrations.RunPython(deduplicate_service_reviews, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='servicereview',
            constraint=models.UniqueConstraint(fields=('client', 'item_type', 'item_id'), name='unique_client_service_review'),
        ),
    ]
