# Generated by Django 5.2.7 on 2026-09-07 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.CharField(default='Nutrition', max_length=100),
        ),
    ]
