# Generated by Django 5.2.12 on 2026-04-06 14:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_panel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_premium', models.BooleanField(default=False)),
                ('profile_photo_url', models.CharField(default='default_avatar.png', max_length=255)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True)),
                ('bmi', models.FloatField(blank=True, null=True)),
                ('bmr', models.FloatField(blank=True, null=True)),
                ('is_banned', models.BooleanField(default=False)),
                ('health_history', models.TextField(blank=True, null=True)),
                ('country', models.ForeignKey(blank=True, db_column='country_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_panel.country')),
                ('goal', models.ForeignKey(blank=True, db_column='goal_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_panel.goal')),
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'clients',
            },
        ),
        migrations.CreateModel(
            name='AICalorieLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(blank=True, max_length=255, null=True)),
                ('segmented_image_url', models.CharField(blank=True, max_length=255, null=True)),
                ('meal_type', models.CharField(blank=True, choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack')], max_length=20, null=True)),
                ('ai_raw_prediction', models.JSONField(blank=True, null=True)),
                ('user_final_log', models.JSONField(blank=True, null=True)),
                ('total_calories', models.FloatField(blank=True, null=True)),
                ('total_protein', models.FloatField(blank=True, null=True)),
                ('total_carbs', models.FloatField(blank=True, null=True)),
                ('total_fats', models.FloatField(blank=True, null=True)),
                ('glycemic_index_rating', models.CharField(blank=True, choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=10, null=True)),
                ('is_validated_by_user', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('pending_user_review', 'Pending User Review'), ('saved', 'Saved'), ('discarded', 'Discarded'), ('failed', 'Failed')], default='processing', max_length=30)),
                ('entry_type', models.CharField(blank=True, choices=[('ai_vision', 'AI Vision'), ('manual_input', 'Manual Input')], max_length=20, null=True)),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(db_column='client_id', on_delete=django.db.models.deletion.CASCADE, to='client.client')),
            ],
            options={
                'db_table': 'ai_calorie_logs',
            },
        ),
        migrations.CreateModel(
            name='PremiumSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(blank=True, max_length=50, null=True)),
                ('amount_paid', models.FloatField(blank=True, null=True)),
                ('transaction_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('client', models.ForeignKey(db_column='client_id', on_delete=django.db.models.deletion.CASCADE, to='client.client')),
            ],
            options={
                'db_table': 'premium_subscriptions',
            },
        ),
        migrations.CreateModel(
            name='DailyProgressMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_calories_consumed', models.FloatField(default=0)),
                ('total_fats_consumed', models.FloatField(default=0)),
                ('total_carbs_consumed', models.FloatField(default=0)),
                ('total_protein_consumed', models.FloatField(default=0)),
                ('target_calories', models.FloatField(blank=True, null=True)),
                ('target_fats', models.FloatField(blank=True, null=True)),
                ('target_carbs', models.FloatField(blank=True, null=True)),
                ('target_protein', models.FloatField(blank=True, null=True)),
                ('is_goal_achieved', models.BooleanField(default=False)),
                ('log_date', models.DateField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(db_column='client_id', on_delete=django.db.models.deletion.CASCADE, to='client.client')),
            ],
            options={
                'db_table': 'daily_progress_metrics',
                'unique_together': {('client', 'log_date')},
            },
        ),
    ]
