# Generated by Django 5.2.7 on 2026-04-21 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_client_target_calories_client_target_carbs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='activity_level',
            field=models.CharField(blank=True, choices=[('sedentary', 'Sedentary'), ('moderate', 'Moderate'), ('very_active', 'Very Active')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='diet',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('omnivore', 'Omnivore'), ('vegetarian', 'Vegetarian'), ('vegan', 'Vegan'), ('keto', 'Keto'), ('paleo', 'Paleo')], max_length=20, null=True),
        ),
    ]
