# Generated by Django 5.2.12 on 2026-04-06 14:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_panel', '0001_initial'),
        ('client', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'languages',
            },
        ),
        migrations.CreateModel(
            name='Nutritionist',
            fields=[
                ('nutritionist_id', models.AutoField(primary_key=True, serialize=False)),
                ('profile_photo_url', models.CharField(default='default_nutri.png', max_length=255)),
                ('certification_ref', models.CharField(blank=True, max_length=255, null=True)),
                ('cert_image_url', models.CharField(blank=True, max_length=255, null=True)),
                ('years_experience', models.IntegerField(blank=True, null=True)),
                ('consultation_price', models.FloatField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('rating', models.FloatField(default=0)),
                ('country', models.ForeignKey(blank=True, db_column='country_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_panel.country')),
                ('specialization', models.ForeignKey(blank=True, db_column='specialization_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_panel.specialization')),
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'nutritionists',
            },
        ),
        migrations.CreateModel(
            name='NutritionistAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Sunday'), (1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('nutritionist', models.ForeignKey(db_column='nutritionist_id', on_delete=django.db.models.deletion.CASCADE, to='nutritionist.nutritionist')),
            ],
            options={
                'db_table': 'nutritionist_availability',
            },
        ),
        migrations.CreateModel(
            name='NutritionistHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holiday_date', models.DateField()),
                ('nutritionist', models.ForeignKey(db_column='nutritionist_id', on_delete=django.db.models.deletion.CASCADE, to='nutritionist.nutritionist')),
            ],
            options={
                'db_table': 'nutritionist_holidays',
            },
        ),
        migrations.CreateModel(
            name='PatientNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(db_column='client_id', on_delete=django.db.models.deletion.CASCADE, to='client.client')),
                ('nutritionist', models.ForeignKey(db_column='nutritionist_id', on_delete=django.db.models.deletion.CASCADE, to='nutritionist.nutritionist')),
            ],
            options={
                'db_table': 'patient_notes',
            },
        ),
        migrations.CreateModel(
            name='NutritionistLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.ForeignKey(db_column='language_id', on_delete=django.db.models.deletion.CASCADE, to='nutritionist.language')),
                ('nutritionist', models.ForeignKey(db_column='nutritionist_id', on_delete=django.db.models.deletion.CASCADE, to='nutritionist.nutritionist')),
            ],
            options={
                'db_table': 'nutritionist_languages',
                'unique_together': {('nutritionist', 'language')},
            },
        ),
        migrations.CreateModel(
            name='NutritionistPatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_type', models.CharField(blank=True, choices=[('from_custom_plan', 'From Custom Plan'), ('free_consultation', 'Free Consultation')], max_length=50, null=True)),
                ('first_consultation_date', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(db_column='client_id', on_delete=django.db.models.deletion.CASCADE, to='client.client')),
                ('nutritionist', models.ForeignKey(db_column='nutritionist_id', on_delete=django.db.models.deletion.CASCADE, to='nutritionist.nutritionist')),
            ],
            options={
                'db_table': 'nutritionist_patients',
                'unique_together': {('nutritionist', 'client')},
            },
        ),
    ]
