# Generated by Django 5.2.12 on 2026-04-07 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutritionist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutritionist',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='nutritionist',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nutritionist',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
