# Generated by Django 5.2.7 on 2026-04-07 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutritionist', '0002_nutritionist_approval_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutritionistlanguage',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
